version: "2.0"
services:
  ganache:
    hostname: chain
    build: .
    ports:
      - "8545:8545"
  payment_service:
    build: ./payment_service
    ports:
      - "4000:4000"
    depends_on:
      - ganache
  process_notification:
    build: ./server_modules/processNotifications
    depends_on:
      - ganache

